# Generated by Django 3.2.3 on 2021-06-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='company'),
        ),
    ]
