# Generated by Django 3.2.3 on 2021-07-07 11:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210707_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='post_detail_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='post detail'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='post_detail_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='post detail'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='post_detail_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='post detail'),
        ),
    ]
