# Generated by Django 3.2.3 on 2021-06-04 04:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='long_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='long_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='long_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='short_description_uz',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='title_en',
            field=models.CharField(max_length=25, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='title_ru',
            field=models.CharField(max_length=25, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='title_uz',
            field=models.CharField(max_length=25, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='name_en',
            field=models.CharField(max_length=25, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='name_ru',
            field=models.CharField(max_length=25, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='name_uz',
            field=models.CharField(max_length=25, null=True, verbose_name='name'),
        ),
    ]
