# Generated by Django 3.2.3 on 2021-06-11 13:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.CharField(max_length=255, verbose_name='content')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='long_description')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
            },
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='long_description_en',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='long_description_ru',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='long_description_uz',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='short_description_uz',
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='content',
            field=models.CharField(default=1, max_length=255, verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='content_en',
            field=models.CharField(max_length=255, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='content_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='content_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='content'),
        ),
    ]
