# Generated by Django 3.2.3 on 2021-06-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20210611_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammodel',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='teammodel',
            name='image2',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
    ]
