# Generated by Django 3.2.3 on 2021-06-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_teammodel_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='phone',
        ),
    ]
