# Generated by Django 3.2.3 on 2021-07-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_awesomeplacemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesomeplacemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
    ]
