# Generated by Django 3.2.3 on 2021-06-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='product',
            new_name='service',
        ),
    ]
