# Generated by Django 3.2.3 on 2021-07-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_product_ordermodel_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='created_at'),
        ),
    ]
