# Generated by Django 3.2.3 on 2021-06-09 10:38

import ckeditor.fields
from django.db import migrations, models

from datetime import datetime


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0006_blogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now(), verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=25, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_ru',
            field=models.CharField(max_length=25, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_uz',
            field=models.CharField(max_length=25, null=True, verbose_name='title'),
        ),
    ]
