# Generated by Django 3.2.3 on 2021-06-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210609_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='created_at',
        ),
    ]
