# Generated by Django 3.2.3 on 2021-06-09 10:51
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_blogmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now(), verbose_name='created_at'),
            preserve_default=False,
        ),
    ]
