# Generated by Django 3.2.3 on 2021-06-09 10:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_blogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='title')),
                ('title_en', models.CharField(max_length=25, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=25, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=25, null=True, verbose_name='title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='content')),
                ('content_uz', ckeditor.fields.RichTextField(null=True, verbose_name='content')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='content')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
