# Generated by Django 3.2.3 on 2021-06-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(verbose_name='created_at'),
        ),
    ]
