# Generated by Django 3.2.3 on 2021-06-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_blogmodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='created_at',
        ),
    ]
