# Generated by Django 3.2.3 on 2021-07-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_callmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callmodel',
            name='call',
            field=models.CharField(max_length=25, verbose_name='call'),
        ),
    ]
